const table = [
  {
    place: 1,
    name: 'Betard Sparta Wrocław',
    matches: 6,
    points: 12,
    smallPoints: '+46',
    wins: 6,
    draws: 0,
    loses: 0,
    homeWins: 3,
    homeLoses: 0,
    awayWins: 3,
    awayLoses: 0,
    bonuses: 0,
    logo: 'wroclaw_128.png'
  },
  {
    place: 4,
    name: 'Fogo Unia Leszno',
    matches: 6,
    points: 6,
    smallPoints: '-42',
    wins: 3,
    draws: 0,
    loses: 3,
    homeWins: 2,
    homeLoses: 1,
    awayWins: 1,
    awayLoses: 2,
    bonuses: 0,
    logo: 'leszno_128.png'
  },
  {
    place: 7,
    name: 'Ebut.pl Stal Gorzów',
    matches: 5,
    points: 3,
    smallPoints: '-7',
    wins: 1,
    draws: 1,
    loses: 3,
    homeWins: 1,
    homeLoses: 1,
    awayWins: 0,
    awayLoses: 2,
    bonuses: 0,
    logo: 'gorzow_128.png'
  },
  {
    place: 2,
    name: 'Platinum Motor Lublin',
    matches: 5,
    points: 8,
    smallPoints: '+75',
    wins: 4,
    draws: 0,
    loses: 1,
    homeWins: 2,
    homeLoses: 1,
    awayWins: 2,
    awayLoses: 0,
    bonuses: 0,
    logo: 'lublin_128.png'
  },
  {
    place: 6,
    name: 'For Nature Solutions KS Apator Toruń',
    matches: 5,
    points: 4,
    smallPoints: '-14',
    wins: 2,
    draws: 0,
    loses: 3,
    homeWins: 2,
    homeLoses: 1,
    awayWins: 0,
    awayLoses: 2,
    bonuses: 0,
    logo: 'torun_128.png'
  },
  {
    place: 3,
    name: 'Tauron Włókniarz Częstochowa',
    matches: 6,
    points: 6,
    smallPoints: '20',
    wins: 2,
    draws: 2,
    loses: 2,
    homeWins: 1,
    homeLoses: 1,
    awayWins: 1,
    awayLoses: 1,
    bonuses: 0,
    logo: 'czestochowa_128.png'
  },
  {
    place: 8,
    name: 'ZOOLeszcz GKM Grudziądz',
    matches: 6,
    points: 1,
    smallPoints: '-50',
    wins: 0,
    draws: 1,
    loses: 5,
    homeWins: 0,
    homeLoses: 2,
    awayWins: 0,
    awayLoses: 3,
    bonuses: 0,
    logo: 'grudziadz_128.png'
  },
  {
    place: 5,
    name: 'Cellfast Wilki Krosno',
    matches: 5,
    points: 4,
    smallPoints: '-28',
    wins: 2,
    draws: 0,
    loses: 3,
    homeWins: 2,
    homeLoses: 0,
    awayWins: 0,
    awayLoses: 3,
    bonuses: 0,
    logo: 'krosno_128.png'
  }
];

export default table;
